# Google Cloud Build - Staging Pipeline
steps:
  # Install Flutter
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/flutter/flutter.git', '-b', 'stable', '--depth', '1']

  # Get Flutter dependencies
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        apt-get update && apt-get install -y unzip curl
        export PATH="$$PATH:/workspace/flutter/bin"
        flutter --version
        flutter pub get

  # Run tests
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        apt-get update && apt-get install -y unzip curl
        export PATH="$$PATH:/workspace/flutter/bin"
        flutter test

  # Build web app
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        apt-get update && apt-get install -y unzip curl
        export PATH="$$PATH:/workspace/flutter/bin"
        flutter build web --release

  # Deploy to Firebase Staging
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase use --project fitness-tracker-8d0ae
        firebase deploy --only hosting --project fitness-tracker-8d0ae

  # Build Android with proper SDK setup
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        apt-get update && apt-get install -y unzip curl wget openjdk-17-jdk
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        
        # Install Android SDK
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip -q commandlinetools-linux-8512546_latest.zip
        mkdir -p /android-sdk/cmdline-tools
        mv cmdline-tools /android-sdk/cmdline-tools/latest
        export ANDROID_HOME=/android-sdk
        export PATH="$$PATH:$$ANDROID_HOME/cmdline-tools/latest/bin:$$ANDROID_HOME/platform-tools"
        
        # Accept licenses non-interactively and install required packages
        mkdir -p $$ANDROID_HOME/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $$ANDROID_HOME/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > $$ANDROID_HOME/licenses/android-sdk-preview-license
        echo "d975f751698a77b662f1254ddbeed3901e976f5a" > $$ANDROID_HOME/licenses/intel-android-extra-license
        sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"
        
        # Setup Flutter and build Android
        export PATH="$$PATH:/workspace/flutter/bin"
        flutter build apk --release
        flutter build appbundle --release

# Store build artifacts
artifacts:
  objects:
    location: 'gs://fitness-tracker-8d0ae-artifacts'
    paths: 
      - 'build/app/outputs/flutter-apk/app-release.apk'
      - 'build/app/outputs/bundle/release/app-release.aab'
      - 'build/web/**/*'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Fast builds

timeout: '1200s'  # 20 minutes max