// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhGuF5F2ciYlz4_AVeInRgielpeMwWHzw',
    appId: '1:362525403590:web:3110155a85fba0a0e36ac7',
    messagingSenderId: '362525403590',
    projectId: 'samaan-ai-staging-2025',
    authDomain: 'samaan-ai-staging-2025.firebaseapp.com',
    storageBucket: 'samaan-ai-staging-2025.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY_HERE', // You need to replace this from the Android app config in Firebase
    appId: 'YOUR_ANDROID_APP_ID_HERE', // You need to replace this from the Android app config in Firebase
    messagingSenderId: '362525403590',
    projectId: 'samaan-ai-staging-2025',
    storageBucket: 'samaan-ai-staging-2025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY_HERE', // You need to replace this from the iOS app config in Firebase
    appId: 'YOUR_IOS_APP_ID_HERE', // You need to replace this from the iOS app config in Firebase
    messagingSenderId: '362525403590',
    projectId: 'samaan-ai-staging-2025',
    storageBucket: 'samaan-ai-staging-2025.appspot.com',
    iosBundleId: 'com.samaanai.productivityhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhGuF5F2ciYlz4_AVeInRgielpeMwWHzw',
    appId: '1:362525403590:web:3110155a85fba0a0e36ac7', // macOS uses web credentials
    messagingSenderId: '362525403590',
    projectId: 'samaan-ai-staging-2025',
    storageBucket: 'samaan-ai-staging-2025.appspot.com',
    iosBundleId: 'com.samaanai.productivityhealth',
  );
}
